// <auto-generated />
namespace CCWOnlineAPIServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class test6231 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test6231));
        
        string IMigrationMetadata.Id
        {
            get { return "201706230235206_test6231"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
